# Generated by Django 3.1 on 2021-02-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_invite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='messsage',
            new_name='message',
        ),
    ]
