# Generated by Django 3.1 on 2021-02-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_employee'),
        ('users', '0009_auto_20210224_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='jobs.job'),
        ),
    ]
