# Generated by Django 3.1 on 2021-02-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_wish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/users/images.png', upload_to='media/users', verbose_name='image'),
        ),
    ]
