# Generated by Django 3.1 on 2021-04-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210407_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='job_portal/users/images_abax4v.png', upload_to='users/', verbose_name='image'),
        ),
    ]
