# Generated by Django 3.1 on 2021-04-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210407_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='job_portal/users/images_n40np7.png', upload_to='users/', verbose_name='image'),
        ),
    ]
