# Generated by Django 2.1.15 on 2021-02-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=30)),
                ('job_type', models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('Temporary', 'Temporary')], default=None, max_length=30)),
                ('location', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None)),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=None, editable=False)),
            ],
        ),
    ]
