# Generated by Django 3.1 on 2021-03-10 14:05

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_quill.fields.QuillField(default=None),
        ),
    ]
