# Generated by Django 3.1 on 2021-03-10 14:51

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tweet',
            field=django_quill.fields.QuillField(blank=True, max_length=500, verbose_name='Resume'),
        ),
    ]
