# Generated by Django 3.1 on 2021-02-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='happy_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('job_type', models.CharField(max_length=300, verbose_name='Job Type')),
                ('tweet', models.CharField(max_length=500, verbose_name='Tweet')),
                ('image', models.ImageField(default='media/users/images.png', upload_to='media/users', verbose_name='image')),
            ],
        ),
    ]
