# Generated by Django 3.1 on 2021-02-26 13:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happy_blog',
            name='tweet',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, verbose_name='Resume'),
        ),
    ]
