# Generated by Django 3.1 on 2021-02-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_blog', '0003_auto_20210226_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happy_blog',
            name='image',
            field=models.ImageField(default='media/happy_blog/images.png', upload_to='happy_blog', verbose_name='image'),
        ),
    ]
