# Generated by Django 3.1 on 2021-03-10 14:51

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('happy_blog', '0005_auto_20210226_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happy_blog',
            name='tweet',
            field=django_quill.fields.QuillField(blank=True, max_length=300, verbose_name='Resume'),
        ),
    ]
